# Generated by Django 5.1.15 on 2026-07-24 05:39

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Chatbot',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier for this record.', primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Timestamp when this record was created.')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when this record was last updated.')),
                ('is_deleted', models.BooleanField(default=False, help_text='Whether this record has been soft deleted.')),
                ('deleted_at', models.DateTimeField(blank=True, help_text='Timestamp when this record was soft deleted.', null=True)),
                ('name', models.CharField(help_text='Name of the chatbot.', max_length=100)),
                ('slug', models.SlugField(help_text='URL-friendly identifier.', max_length=120, unique=True)),
                ('description', models.TextField(blank=True, help_text="Description of the chatbot's purpose.")),
                ('avatar', models.ImageField(blank=True, help_text='Chatbot avatar image.', null=True, upload_to='chatbot_avatars/')),
                ('system_prompt', models.TextField(default="You are a helpful customer support assistant. Answer questions only based on the provided context. If you don't know the answer based on the context, say 'I don't know based on the provided knowledge.'", help_text='System prompt for the LLM.')),
                ('temperature', models.FloatField(default=0.7, help_text='Temperature for LLM generation (0.0 to 2.0).')),
                ('top_p', models.FloatField(default=0.9, help_text='Top P for LLM generation (0.0 to 1.0).')),
                ('max_context_length', models.IntegerField(default=4096, help_text='Maximum context length for the LLM.')),
                ('embedding_model', models.CharField(default='BAAI/bge-small-en-v1.5', help_text='Embedding model to use.', max_length=100)),
                ('llm_model', models.CharField(default='llama3.2', help_text='LLM model to use.', max_length=100)),
                ('top_k', models.IntegerField(default=5, help_text='Number of similar chunks to retrieve.')),
                ('chunk_size', models.IntegerField(default=500, help_text='Size of text chunks for embedding.')),
                ('chunk_overlap', models.IntegerField(default=50, help_text='Overlap between chunks.')),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('draft', 'Draft')], default='draft', help_text='Current status of the chatbot.', max_length=20)),
                ('total_conversations', models.IntegerField(default=0, help_text='Total number of conversations.')),
                ('total_messages', models.IntegerField(default=0, help_text='Total number of messages.')),
                ('last_used_at', models.DateTimeField(blank=True, help_text='When the chatbot was last used.', null=True)),
                ('owner', models.ForeignKey(help_text='The user who owns this chatbot.', on_delete=django.db.models.deletion.CASCADE, related_name='chatbots', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Chatbot',
                'verbose_name_plural': 'Chatbots',
                'ordering': ['-created_at'],
            },
        ),
    ]
