# Generated by Django 6.0.7 on 2026-07-25 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbots', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatbot',
            name='allow_embed',
            field=models.BooleanField(default=True, help_text='Allow this chatbot to be embedded on external websites.'),
        ),
    ]
