# Generated by Django 6.0.7 on 2026-07-26 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbots', '0002_chatbot_allow_embed'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatbot',
            name='offline_message',
            field=models.CharField(blank=True, default='', help_text='Message shown when the chatbot is unavailable.', max_length=500),
        ),
        migrations.AddField(
            model_name='chatbot',
            name='placeholder_text',
            field=models.CharField(default='Type your message...', help_text='Chat input placeholder text.', max_length=100),
        ),
        migrations.AddField(
            model_name='chatbot',
            name='welcome_message',
            field=models.CharField(default='How can I help you?', help_text='Greeting message shown when chat opens.', max_length=500),
        ),
        migrations.AddField(
            model_name='chatbot',
            name='widget_agent_msg_color',
            field=models.CharField(default='#ffffff', help_text='Agent message bubble color (hex).', max_length=7),
        ),
        migrations.AddField(
            model_name='chatbot',
            name='widget_background_color',
            field=models.CharField(default='#ffffff', help_text='Chat background color (hex).', max_length=7),
        ),
        migrations.AddField(
            model_name='chatbot',
            name='widget_header_color',
            field=models.CharField(default='#ffffff', help_text='Header background color (hex).', max_length=7),
        ),
        migrations.AddField(
            model_name='chatbot',
            name='widget_primary_color',
            field=models.CharField(default='#6366f1', help_text='Primary/accent color (hex).', max_length=7),
        ),
        migrations.AddField(
            model_name='chatbot',
            name='widget_user_msg_color',
            field=models.CharField(default='#6366f1', help_text='User message bubble color (hex).', max_length=7),
        ),
    ]
