# Generated by Django 5.1.15 on 2026-07-24 05:39

import django.contrib.auth.models
import django.contrib.auth.validators
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier for this user.', primary_key=True, serialize=False)),
                ('email', models.EmailField(help_text="User's email address.", max_length=254, unique=True)),
                ('avatar', models.ImageField(blank=True, help_text="User's profile avatar.", null=True, upload_to='avatars/')),
                ('bio', models.TextField(blank=True, help_text="User's biography.", max_length=500)),
                ('company', models.CharField(blank=True, help_text="User's company name.", max_length=100)),
                ('job_title', models.CharField(blank=True, help_text="User's job title.", max_length=100)),
                ('phone', models.CharField(blank=True, help_text="User's phone number.", max_length=20)),
                ('timezone', models.CharField(default='UTC', help_text="User's timezone.", max_length=50)),
                ('is_email_verified', models.BooleanField(default=False, help_text="Whether the user's email has been verified.")),
                ('last_login_ip', models.GenericIPAddressField(blank=True, help_text='IP address of the last login.', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Timestamp when this user was created.')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when this user was last updated.')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'User',
                'verbose_name_plural': 'Users',
                'ordering': ['-created_at'],
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
    ]
