# Generated by Django 6.0.7 on 2026-07-29 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('CEO', 'CEO'), ('customer', 'Customer')], default='customer', help_text="User's role in the system.", max_length=20),
        ),
    ]
