# Generated by Django 6.0.7 on 2026-07-29 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_user_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='max_chatbots',
            field=models.IntegerField(default=1, help_text='Maximum number of chatbots this user can create. Set to 0 for unlimited.'),
        ),
    ]
