# Generated by Django 5.1.15 on 2026-07-24 05:39

import django.db.models.deletion
import pgvector.django.vector
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('chatbots', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='KnowledgeBase',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier for this record.', primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Timestamp when this record was created.')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when this record was last updated.')),
                ('is_deleted', models.BooleanField(default=False, help_text='Whether this record has been soft deleted.')),
                ('deleted_at', models.DateTimeField(blank=True, help_text='Timestamp when this record was soft deleted.', null=True)),
                ('name', models.CharField(help_text='Name of the knowledge base.', max_length=200)),
                ('description', models.TextField(blank=True, help_text='Description of the knowledge base.')),
                ('total_documents', models.IntegerField(default=0, help_text='Total number of documents.')),
                ('total_chunks', models.IntegerField(default=0, help_text='Total number of chunks.')),
                ('total_tokens', models.IntegerField(default=0, help_text='Total number of tokens.')),
                ('chatbot', models.OneToOneField(help_text='The chatbot this knowledge base belongs to.', on_delete=django.db.models.deletion.CASCADE, related_name='knowledge_bases', to='chatbots.chatbot')),
            ],
            options={
                'verbose_name': 'Knowledge Base',
                'verbose_name_plural': 'Knowledge Bases',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='QAPair',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier for this record.', primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Timestamp when this record was created.')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when this record was last updated.')),
                ('is_deleted', models.BooleanField(default=False, help_text='Whether this record has been soft deleted.')),
                ('deleted_at', models.DateTimeField(blank=True, help_text='Timestamp when this record was soft deleted.', null=True)),
                ('question', models.TextField(help_text='The question.')),
                ('answer', models.TextField(help_text='The answer.')),
                ('embedding', pgvector.django.vector.VectorField(blank=True, dimensions=384, help_text='Vector embedding of the question.', null=True)),
                ('category', models.CharField(blank=True, help_text='Optional category for the QA pair.', max_length=100)),
                ('is_active', models.BooleanField(default=True, help_text='Whether this QA pair is active.')),
                ('knowledge_base', models.ForeignKey(help_text='The knowledge base this QA pair belongs to.', on_delete=django.db.models.deletion.CASCADE, related_name='qa_pairs', to='knowledge.knowledgebase')),
            ],
            options={
                'verbose_name': 'QA Pair',
                'verbose_name_plural': 'QA Pairs',
                'ordering': ['-created_at'],
            },
        ),
    ]
