# Generated by Django 5.1.15 on 2026-07-24 05:39

import django.db.models.deletion
import pgvector.django.vector
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('knowledge', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier for this record.', primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Timestamp when this record was created.')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when this record was last updated.')),
                ('is_deleted', models.BooleanField(default=False, help_text='Whether this record has been soft deleted.')),
                ('deleted_at', models.DateTimeField(blank=True, help_text='Timestamp when this record was soft deleted.', null=True)),
                ('title', models.CharField(help_text='Document title.', max_length=200)),
                ('file', models.FileField(blank=True, help_text='Uploaded file.', null=True, upload_to='documents/%Y/%m/')),
                ('document_type', models.CharField(choices=[('pdf', 'PDF'), ('docx', 'DOCX'), ('txt', 'Text'), ('md', 'Markdown'), ('qa', 'Q&A Pair')], help_text='Type of document.', max_length=10)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', help_text='Processing status.', max_length=20)),
                ('file_size', models.IntegerField(default=0, help_text='File size in bytes.')),
                ('page_count', models.IntegerField(default=0, help_text='Number of pages (for PDFs).')),
                ('chunk_count', models.IntegerField(default=0, help_text='Number of chunks created.')),
                ('error_message', models.TextField(blank=True, help_text='Error message if processing failed.')),
                ('processed_at', models.DateTimeField(blank=True, help_text='When the document was processed.', null=True)),
                ('metadata', models.JSONField(blank=True, default=dict, help_text='Additional document metadata.')),
                ('knowledge_base', models.ForeignKey(help_text='The knowledge base this document belongs to.', on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='knowledge.knowledgebase')),
            ],
            options={
                'verbose_name': 'Document',
                'verbose_name_plural': 'Documents',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DocumentChunk',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier for this record.', primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Timestamp when this record was created.')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when this record was last updated.')),
                ('is_deleted', models.BooleanField(default=False, help_text='Whether this record has been soft deleted.')),
                ('deleted_at', models.DateTimeField(blank=True, help_text='Timestamp when this record was soft deleted.', null=True)),
                ('content', models.TextField(help_text='The text content of the chunk.')),
                ('embedding', pgvector.django.vector.VectorField(blank=True, dimensions=384, help_text='Vector embedding of the chunk content.', null=True)),
                ('chunk_index', models.IntegerField(help_text='Index of this chunk in the document.')),
                ('page_number', models.IntegerField(blank=True, help_text='Page number for PDF documents.', null=True)),
                ('token_count', models.IntegerField(default=0, help_text='Number of tokens in this chunk.')),
                ('metadata', models.JSONField(blank=True, default=dict, help_text='Additional metadata for the chunk.')),
                ('document', models.ForeignKey(help_text='The document this chunk belongs to.', on_delete=django.db.models.deletion.CASCADE, related_name='chunks', to='documents.document')),
            ],
            options={
                'verbose_name': 'Document Chunk',
                'verbose_name_plural': 'Document Chunks',
                'ordering': ['document', 'chunk_index'],
            },
        ),
        migrations.CreateModel(
            name='DocumentProcessLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier for this record.', primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Timestamp when this record was created.')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when this record was last updated.')),
                ('is_deleted', models.BooleanField(default=False, help_text='Whether this record has been soft deleted.')),
                ('deleted_at', models.DateTimeField(blank=True, help_text='Timestamp when this record was soft deleted.', null=True)),
                ('event', models.CharField(help_text="Event type (e.g., 'upload', 'extract', 'chunk', 'embed').", max_length=50)),
                ('status', models.CharField(choices=[('started', 'Started'), ('completed', 'Completed'), ('failed', 'Failed')], help_text='Event status.', max_length=20)),
                ('message', models.TextField(blank=True, help_text='Log message.')),
                ('duration', models.FloatField(blank=True, help_text='Duration in seconds.', null=True)),
                ('document', models.ForeignKey(help_text='The document this log belongs to.', on_delete=django.db.models.deletion.CASCADE, related_name='process_logs', to='documents.document')),
            ],
            options={
                'verbose_name': 'Document Process Log',
                'verbose_name_plural': 'Document Process Logs',
                'ordering': ['-created_at'],
            },
        ),
    ]
