# Generated by Django 5.1.15 on 2026-07-24 05:39

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('chatbots', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Conversation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier for this record.', primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Timestamp when this record was created.')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when this record was last updated.')),
                ('is_deleted', models.BooleanField(default=False, help_text='Whether this record has been soft deleted.')),
                ('deleted_at', models.DateTimeField(blank=True, help_text='Timestamp when this record was soft deleted.', null=True)),
                ('title', models.CharField(blank=True, help_text='Conversation title.', max_length=200)),
                ('session_id', models.CharField(help_text='Unique session identifier.', max_length=100, unique=True)),
                ('is_active', models.BooleanField(default=True, help_text='Whether the conversation is active.')),
                ('message_count', models.IntegerField(default=0, help_text='Number of messages in this conversation.')),
                ('last_message_at', models.DateTimeField(blank=True, help_text='Timestamp of the last message.', null=True)),
                ('chatbot', models.ForeignKey(help_text='The chatbot in this conversation.', on_delete=django.db.models.deletion.CASCADE, related_name='conversations', to='chatbots.chatbot')),
                ('user', models.ForeignKey(blank=True, help_text='The user (if authenticated).', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='conversations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Conversation',
                'verbose_name_plural': 'Conversations',
                'ordering': ['-last_message_at'],
            },
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier for this record.', primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Timestamp when this record was created.')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when this record was last updated.')),
                ('is_deleted', models.BooleanField(default=False, help_text='Whether this record has been soft deleted.')),
                ('deleted_at', models.DateTimeField(blank=True, help_text='Timestamp when this record was soft deleted.', null=True)),
                ('role', models.CharField(choices=[('user', 'User'), ('assistant', 'Assistant'), ('system', 'System')], help_text='Message role (user, assistant, or system).', max_length=20)),
                ('content', models.TextField(help_text='Message content.')),
                ('metadata', models.JSONField(blank=True, default=dict, help_text='Additional message metadata (sources, model used, etc.).')),
                ('tokens_used', models.IntegerField(default=0, help_text='Number of tokens used in this message.')),
                ('conversation', models.ForeignKey(help_text='The conversation this message belongs to.', on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='chat.conversation')),
            ],
            options={
                'verbose_name': 'Message',
                'verbose_name_plural': 'Messages',
                'ordering': ['created_at'],
            },
        ),
    ]
